# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/79ad1bfb-f173-45b4-9ec8-eee361d5f074";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."nixosLuks" = {
    allowDiscards = true;
    device = "/dev/disk/by-uuid/dca79447-9052-406c-8cf0-2eb7c7d4f0c9";
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/79ad1bfb-f173-45b4-9ec8-eee361d5f074";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/79ad1bfb-f173-45b4-9ec8-eee361d5f074";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F8AD-268F";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4720c2f9-ea1e-4d8c-8733-872f9486e77d"; }
    ];

}
