#!/bin/sh

source ${HOME}/.config/restic/env

CASTLE_BACKUP_DIR=${HOME}/.var/backup/castle/

if [ ! -d ${CASTLE_BACKUP_DIR} ] ; then
  mkdir -p ${CASTLE_BACKUP_DIR}
fi

sshfs root@castle.danieldk.eu:/ ${CASTLE_BACKUP_DIR}

if [ -d ${CASTLE_BACKUP_DIR}/srv/www/danieldk.eu ]; then
  restic -r sftp:umbrella:/data/castle-backup backup --tag=www ${CASTLE_BACKUP_DIR}/srv/www
  restic -r sftp:umbrella:/data/castle-backup backup --tag=git ${CASTLE_BACKUP_DIR}/var/lib/gitolite
restic -r sftp:umbrella:/data/castle-backup forget --prune -H 10 -d 10 -w 10 -m 10 -y 10 
else
  >&2 echo "Could not find danieldk.eu in castle backup directory."
fi

fusermount -u ${CASTLE_BACKUP_DIR}
