#!/bin/sh

source ${HOME}/.config/restic/env

restic -r sftp:umbrella:/data/daniel-backup backup --tag=dropbox ~/Dropbox

restic -r sftp:umbrella:/data/daniel-backup backup -e target --tag=git ~/git

restic -r sftp:umbrella:/data/daniel-backup forget --prune -H 10 -d 10 -w 10 -m 10 -y 10 
