# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "a368813c5e648fee92e5f6c30e3944ff9d5e8895";
      sha256 = "1sjxs2lwc8jpln80s4rlzp7nprbcljhy5mz4rf9995gq93wqnym5";
    };
  }
  {
    goPackagePath = "github.com/danieldk/conllx";
    fetch = {
      type = "git";
      url = "https://github.com/danieldk/conllx";
      rev = "26880bc037f79039f751732080e61ced4291f40a";
      sha256 = "16kd0r5nclksg2ibz20b20vrl3nivqr4xc0z0078yf35bgxdz8b0";
    };
  }
]
