#!/bin/sh

MUPDF=$(which mupdf-gl)

if [ $(uname) = "Linux" ]; then
  if [ $# -eq 0 ]; then
    echo "Usage: $0 [OPTIONS] filename"
    exit 1
  fi

  (exec bwrap \
    --ro-bind /nix/store /nix/store \
    --ro-bind /run /run \
    --proc /proc \
    --dev-bind /dev/dri /dev/dri \
    --ro-bind /sys/dev /sys/dev \
    --ro-bind /sys/devices /sys/devices \
    --tmpfs ${HOME} \
    --ro-bind $HOME/.Xauthority $HOME/.Xauthority \
    --ro-bind ${MUPDF} ${MUPDF} \
    --tmpfs /tmp \
    --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0 \
    --ro-bind "${@: -1}" /home/jail/"$(basename "${@: -1}")" \
    --chdir /home/jail \
    --setenv DISPLAY :0 \
    --unshare-all \
    --new-session \
    ${MUPDF} "$(basename "${@: -1}")")
fi
