filetype plugin indent on

" Do not put backups and swap files in the currenty directory.
set backupdir=~/.backup,.,/tmp
set directory=~/.backup,.,/tmp

set nocompatible

syntax on

set modelines=0

set tabstop=2
set shiftwidth=2
"set softtabstop=22
set expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile

let mapleader = ","

set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

" Escape is to far away...
:imap jj <Esc>

set wrap
set textwidth=76
set formatoptions=qrn1
set colorcolumn=+1

set list
set listchars=tab:▸\ ,eol:¬

nnoremap ; :

nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

nnoremap <leader>q gqip

" Toggle paste
set pastetoggle=<F2>
nnoremap <silent> <leader>n :set paste!<CR>

" Vertical split
nnoremap <leader>v <C-w>v<C-w>l

" Horizontal split
nnoremap <leader>w <C-w><C-s><C-w>j

" Simpler window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

set background=dark
colorscheme solarized

if exists('g:colors_name') && colors_name == 'solarized'
  if has('gui_macvim')
    set transparency=0
  endif

  if !has('gui_running') && $TERM_PROGRAM == 'Apple_Terminal'
    let g:solarized_termcolors = &t_Co
    colorscheme solarized
  endif

  call togglebg#map("<F2>")
endif

" git
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gc :Gcommit<cr>
nnoremap <leader>gl :Glog<cr>
nnoremap <leader>go :Git stash pop<cr>
nnoremap <leader>gp :Git push<cr>
nnoremap <leader>gt :Git stash<cr>
nnoremap <leader>gu :Git pull<cr>

" quickfix list
nnoremap <leader>f :cwindow<cr>

" ctrl-p
nnoremap <leader>p :CtrlP<cr>
nnoremap <leader>t :CtrlPTag<cr>

augroup FileType go
  au!
  au FileType go nmap <Leader>d <Plug>(go-def)
  au FileType go nmap <Leader>s <Plug>(go-implements)
  au FileType go nmap <Leader>i <Plug>(go-info)
  au FileType go nmap <leader>c <Plug>(go-coverage)
  au FileType go nmap <Leader>e <Plug>(go-rename)
  au FileType go nmap <leader>b <Plug>(go-build)

  au FileType go nmap <Leader>ds <Plug>(go-def-split)
  au FileType go nmap <Leader>dv <Plug>(go-def-vertical)

  au FileType go nmap <Leader>gd <Plug>(go-doc)
  au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
  au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
augroup END

let g:go_fmt_command = "goimports"

" Kill arrow keys
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
